"""add language to posts

Revision ID: 070693833d80
Revises: 70dd51536d26
Create Date: 2026-01-25 02:53:58.013545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070693833d80'
down_revision = '70dd51536d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
