"""Add phone_number to User

Revision ID: 360feea02103
Revises: 1bdd52d67c9f
Create Date: 2025-10-19 16:41:51.663598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360feea02103'
down_revision = '1bdd52d67c9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=13), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_phone_number'), ['phone_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone_number'))
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
