"""reverd phone_validation

Revision ID: 572d6661521b
Revises: e89b7ff01d69
Create Date: 2025-11-07 16:38:35.777500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572d6661521b'
down_revision = 'e89b7ff01d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
