"""empty message

Revision ID: 7e30bd8ac797
Revises: 360feea02103
Create Date: 2025-10-19 16:57:11.751987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e30bd8ac797'
down_revision = '360feea02103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=13), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_phone_number'), ['phone_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone_number'))
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
