"""empty message

Revision ID: a5c1ff33d457
Revises: 7e30bd8ac797
Create Date: 2025-10-19 17:01:58.389422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c1ff33d457'
down_revision = '7e30bd8ac797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_phone_number'), ['phone_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone_number'))
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
